### ISSUE TITLE
Under which license have you published this?

### ISSUE THREAD

**Issue by wilsncc** [curiositry/undefined-ghost-theme#1]
I would like to use this, but I would need to know first which license it was published with.

Thanks in advance, and thanks for this rather empty theme! 🙇🏻

**Comment by curiositry** [comment]
Thanks for bringing this to my attention @rossdotpink!

 I have added the missing licence file here: https://github.com/curiositry/undefined-ghost-theme/blob/master/LICENSE

IIRC I was originally planning to release this under some even more totally unlicenced lience, but got bogged down in the technicalities of public domain licences. So MIT it is, for now, because that's what I'm familiar with. Is MIT permissive enough for your needs?

**Comment by wilsncc** [comment]
Yes that's perfect. Thank you kindly!
